### ISSUE TITLE
ScrollSpyContainer défaut d'interprétation de l'élément actif

### ISSUE THREAD

**Issue by vit-Cos** [klee-contrib/focus4#188]
Expliquer dans les images mais si le header sticky est assez grand et que le bloc est petit, il est encore visible sous le header et le scrollspy considède que c'est lui qui est sélectionné.

![img1_bug_focus](https://user-images.githubusercontent.com/109680690/219402393-6834bdea-5728-458a-ad4a-43f4a021c418.png)
![img2_bug_focus](https://user-images.githubusercontent.com/109680690/219402426-ea8cabb2-0f81-468d-80a5-7bcddaaaf6fe.png)

**Comment by JabX** [comment]
Corrigé en 11.7.0
