### ISSUE TITLE
Mettre en place une doc de meilleure qualité, avec un showcase de composants digne de ce nom

### ISSUE THREAD

**Issue by JabX** [klee-contrib/focus4#195]
- Revoir la doc sur les formulaires pour la rendre plus facile à suivre, tout en rentrant un peu plus dans le détail
- Faire un doc complète sur comment faire du CSS correctement avec Focus
- Documenter pour de vrai les collections/listes/tableaux
- Partir de la doc autogénérée pour les composants et y inclure une démo (nécessitera probablement de changer de framework pour la doc...)

**Comment by etienne582** [comment]
UPVOTE

**Comment by JabX** [comment]
Initialisé en 11.14 et complété en 11.15 😊
